source [file join [file dirname [info script]] components/COREFIFO_DMA_WR_8GB.tcl]
source [file join [file dirname [info script]] components/COREFIFO_DMA_WR_16GB.tcl]
source [file join [file dirname [info script]] components/dma_write_ddr4_8gb.tcl]
source [file join [file dirname [info script]] components/dma_write_ddr4_16gb.tcl]
source [file join [file dirname [info script]] components/dma_write_apb_reg_ddr4_8gb.tcl]
source [file join [file dirname [info script]] components/dma_write_apb_reg_ddr4_16gb.tcl]
