#!/usr/bin/env python3
"""Write the one line of Verilog that decides whether a build uses TMR.

The variant used to be selected by editing tracked source: the Makefile
`sed`-ed `src/top.sv` and the pin constraints, ran Libero, and restored them
afterwards. Meanwhile `synth.tcl` took the identifier from `git rev-parse
HEAD`, which describes the *committed* tree. Three of the four images it
produced therefore carried an identifier pointing at source that does not
build them -- and wrong in the direction that inspires confidence.

Nothing is edited now. `src/top.sv` includes this generated file, and this
file is the only thing that differs between a TMR build and a plain one. The
tracked tree is never touched, so `git rev-parse HEAD` is true, and a
dirty-tree check becomes meaningful rather than decorative.

The include resolves without any tool configuration, in both tools that
compile this design:

- Synplify searches "first, the source file directory" for `` `include ``
  (Synplify command reference, `-include_path`), and this is written beside
  `top.sv`;
- Verilator is given `-I<src>` already, and does *not* resolve includes
  relative to the including file unless asked -- which is why this is included
  by plain name rather than by a path.

Generated rather than committed, because a committed copy is a second source
of truth and the two disagree the first time somebody builds the other
variant and forgets to put it back. That is the failure this replaces.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

#: Written beside `top.sv`, because that is where Synplify looks first.
FILENAME = "build_variant.vh"

#: Variants this design is built in. `_tmr` means triple-module redundancy is
#: enabled; `fm`/`em` select the RS-422 pinout and are a constraint choice,
#: not a source one, so they do not appear in this file.
VARIANTS = {
    "fm_tmr": True,
    "em_tmr": True,
    "fm": False,
    "em": False,
}

HEADER = """// GENERATED by script/build_variant.py -- do not edit, do not commit.
//
// Written for variant %(variant)s. This is the only source difference between
// a TMR build and a plain one; everything else is identical, so the commit
// recorded in the programming file describes the source that produced it.
//
// If this file is missing, src/top.sv will not compile. That is deliberate: a
// build with no variant selected is a build nobody can identify afterwards.
"""

TMR_ON = """
// syn_radhardlevel="tmr" is attached to the top-level module in src/top.sv
// when this is defined. Each register becomes three flip-flops that vote.
`define TMR
"""

TMR_OFF = """
// TMR is NOT enabled in this build. The image is roughly a third smaller than
// the equivalent _tmr build, and it must not be flown.
"""


def contents(variant: str) -> str:
    if variant not in VARIANTS:
        raise SystemExit(
            "unknown variant %r. Known variants are %s. A variant that is not "
            "listed would produce an image nothing can identify."
            % (variant, ", ".join(sorted(VARIANTS))))
    return (HEADER % {"variant": variant}
            + (TMR_ON if VARIANTS[variant] else TMR_OFF))


def write(src_dir: Path, variant: str) -> Path:
    target = Path(src_dir) / FILENAME
    fresh = contents(variant)
    # Only when it differs. Rewriting an identical file moves its timestamp,
    # which rebuilds the whole device for no change -- cheap in Verilator,
    # expensive in Libero.
    if not target.is_file() or target.read_text(encoding="utf-8") != fresh:
        target.write_text(fresh, encoding="utf-8")
    return target


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("variant", help="one of: %s" % ", ".join(sorted(VARIANTS)))
    ap.add_argument("--src", type=Path, default=Path("src"),
                    help="directory holding top.sv (default: src)")
    args = ap.parse_args(argv)

    if not args.src.is_dir():
        raise SystemExit("no source directory at %s" % args.src)
    target = write(args.src, args.variant)
    print("%s: TMR %s" % (target, "enabled" if VARIANTS[args.variant]
                          else "DISABLED -- this image must not be flown"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
