/*
 * @file      clock_counter.sv
 * @copyright Copyright (c) 2025 Turion Space. All rights reserved.
 * @author    Chase Whyte (cwhyte@turionspace.com)
 * @date      08/15/2025
 * 
 * @brief     Short description of what this module does.
 * 
 * @section changelog
 * - 08/15/2025: Chase Whyte - Initial implementation
 * 
 */

`timescale 1ns / 100ps
// Selects TMR for this build. Generated by script/build_variant.py and not
// committed: the variant used to be chosen by editing this line in place,
// which meant the commit id recorded in the programming file described
// source that did not build it. Included by plain name so that Synplify
// finds it beside this file and Verilator finds it on -I<src>.
`include "build_variant.vh"
// top
module top #(
    parameter logic [31:0]                                PULSE_WIDTH           = 32'd250,             //minimum detectable pulse width on input signals
    parameter logic [31:0]                                WAIT_TIME_MULT_FACTOR = 32'd50               //mult factor for all wait times, decrease this to improve sim time 
) (
    // Inputs
    input  wire clk,
    input  wire ddr16_nfault_2v5,
    input  wire ddr16_nfault_1v2,
    input  wire ddr16_pgood_2v5,
    input  wire ddr16_pgood_1v2,
    input  wire ddr16_pgood_0v6,
    input  wire ddr8_nfault_2v5,
    input  wire ddr8_nfault_1v2,
    input  wire ddr8_pgood_2v5,
    input  wire ddr8_pgood_1v2,
    input  wire ddr8_pgood_0v6,
    input  wire eps_efuse_pgood,
    input  wire eth1_ctrl,
    input  wire eth1_pgood_1v0,
    input  wire eth1_pgood_1v0a,
    input  wire eth1_pgood_2v5a,
    input  wire eth1_pgood_3v3,
    input  wire eth2_ctrl,
    input  wire eth2_pgood_1v0,
    input  wire eth2_pgood_1v0a,
    input  wire eth2_pgood_2v5a,
    input  wire eth2_pgood_3v3,
    input  wire fpga_nfault_1v0,
    input  wire fpga_pgood_1v0,
    input  wire fpga_pgood_1v0a,
    input  wire fpga_pgood_1v25a,
    input  wire fpga_pgood_1v8,
    input  wire fpga_pgood_1v8_imx,
    input  wire fpga_pgood_2v5a,
    input  wire fpga_pgood_3v3_b4,
    input  wire fpga_pgood_3v3_b5,
    input  wire imx_ctrl,
    input  wire imx_nfault_1v1,
    input  wire imx_pgood_1v1,
    input  wire imx_pgood_1v8,
    input  wire imx_pgood_2v9,
    input  wire imx_pgood_3v3,
    input  wire lvdt_ctrl,
    input  wire lvdt_pgood,
    input  wire lvds_pgood,
    input  wire step_down_nfault_2v2,
    input  wire step_down_nfault_3v0,
    input  wire step_down_nfault_4v0,
    input  wire step_down_pgood_2v2,
    input  wire step_down_pgood_3v0,
    input  wire step_down_pgood_4v0,
    input  wire rs422_ttl_bus_to_farsight_pa3,
    input  wire rs422_ttl_farsight_to_bus_pf,
    input  wire arstn,
    input  wire stepper_pri_ctrl,
    input  wire stepper_pri_nfault,
    input  wire stepper_pri_pgood,
    input  wire stepper_sec_ctrl,
    input  wire stepper_sec_nfault,
    input  wire stepper_sec_pgood,
    output wire ddr16_en_2v5,
    output wire ddr16_en_1v2,
    output wire ddr16_en_0v6,
    output wire ddr8_en_2v5,
    output wire ddr8_en_1v2,
    output wire ddr8_en_0v6,
    output wire ddr16_status_to_pf,
    output wire ddr8_status_to_pf,
    output wire eth1_en_1v0,
    output wire eth1_en_1v0a,
    output wire eth1_en_2v5a,
    output wire eth1_en_3v3,
    output wire eth1_status_to_pf,
    output wire eth2_en_1v0,
    output wire eth2_en_1v0a,
    output wire eth2_en_2v5a,
    output wire eth2_en_3v3,
    output wire eth2_status_to_pf,
    output wire fpga_en_1v0,
    output wire fpga_en_1v0a,
    output wire fpga_en_1v25a,
    output wire fpga_en_1v8,
    output wire fpga_en_1v8_imx,
    output wire fpga_en_2v5a,
    output wire fpga_en_3v3_b4,
    output wire fpga_en_3v3_b5,
    output wire [2:0] fw_version,
    output wire imx_en_1v1,
    output wire imx_en_1v8,
    output wire imx_en_2v9,
    output wire imx_en_3v3,
    output wire imx_status_to_pf,
    output wire lvds_status_to_pf,
    output wire lvdt_en,
    output wire lvdt_status_to_pf,
    output wire lvds_en,
    output wire step_down_en_2v2,
    output wire step_down_en_3v0,
    output wire step_down_en_4v0,
    output wire rs422_ttl_bus_to_farsight_pf,
    output wire rs422_ttl_farsight_to_bus_pa3,
    output wire stepper_pri_en,
    output wire stepper_pri_status_to_pf,
    output wire stepper_sec_en,
    output wire stepper_sec_status_to_pf,
    output wire imx_nshort_1v1,
    output wire imx_nshort_1v8,
    output wire [6:0] debug,
    output wire heartbeat,
    output wire pa3_status_to_pf,
    output wire pf_status_to_pf,
    output wire step_down_status_to_pf,
    output wire [1:0] ddr8_failure_metadata,
    output wire [1:0] ddr16_failure_metadata,
    output wire [2:0] eth1_failure_metadata,
    output wire [2:0] eth2_failure_metadata,
    output wire stepper_pri_failure_metadata,
    output wire stepper_sec_failure_metadata,
    output wire lvdt_failure_metadata,
    output wire [2:0] imx_failure_metadata
`ifdef TMR
) /* synthesis syn_radhardlevel="tmr" */;
`else
);
`endif
//--------------------------------------------------------------------
// Nets
//--------------------------------------------------------------------

wire   [12:0] health_monitor_io_0_baud_val;
wire          health_monitor_io_0_parity_en;
wire          health_monitor_io_0_parity_oddneven;
wire          health_monitor_io_0_uart_bit8;
wire          health_monitor_io_0_uart_csn;
wire          health_monitor_io_0_uart_oen;
wire          health_monitor_io_0_uart_rx;
wire   [7:0]  health_monitor_io_0_uart_tx_data;
wire          health_monitor_io_0_uart_wen;
wire          UART0_0_TX;
wire          UART0_0_TXRDY;

wire          rstn;

//--------------------------------------------------------------------
// Component instances
//--------------------------------------------------------------------
//--------health_monitor_io

health_monitor_io # (
    .PULSE_WIDTH           (PULSE_WIDTH),
    .WAIT_TIME_MULT_FACTOR (WAIT_TIME_MULT_FACTOR)

) health_monitor_io_0 (

    .clk,       //ASIC 50MHz clock
    .arstn,
    .rstn,
    .eps_efuse_pgood,
    .ddr16_nfault_2v5,
    .ddr16_nfault_1v2,
    .ddr16_pgood_2v5,
    .ddr16_pgood_1v2,
    .ddr16_pgood_0v6,
    .ddr8_nfault_2v5,
    .ddr8_nfault_1v2,
    .ddr8_pgood_2v5,
    .ddr8_pgood_1v2,
    .ddr8_pgood_0v6,
    .eth1_ctrl,
    .eth1_pgood_1v0,
    .eth1_pgood_1v0a,
    .eth1_pgood_2v5a,
    .eth1_pgood_3v3,
    .eth2_ctrl,
    .eth2_pgood_1v0,
    .eth2_pgood_1v0a,
    .eth2_pgood_2v5a,
    .eth2_pgood_3v3,
    .fpga_nfault_1v0,
    .fpga_pgood_1v0,
    .fpga_pgood_1v0a,
    .fpga_pgood_1v25a,
    .fpga_pgood_1v8,
    .fpga_pgood_1v8_imx,
    .fpga_pgood_2v5a,
    .fpga_pgood_3v3_b4,
    .fpga_pgood_3v3_b5,
    .imx_ctrl,
    .imx_nfault_1v1,
    .imx_pgood_1v1,
    .imx_pgood_1v8,
    .imx_pgood_2v9,
    .imx_pgood_3v3,
    .lvdt_ctrl,
    .lvdt_pgood,
    .lvds_pgood,
    .step_down_nfault_2v2,
    .step_down_nfault_3v0,
    .step_down_nfault_4v0,
    .step_down_pgood_2v2,
    .step_down_pgood_3v0,
    .step_down_pgood_4v0,
    .stepper_pri_ctrl,
    .stepper_pri_nfault,
    .stepper_pri_pgood,
    .stepper_sec_ctrl,
    .stepper_sec_nfault,
    .stepper_sec_pgood,
    .ddr16_en_2v5,
    .ddr16_en_1v2,
    .ddr16_en_0v6,
    .ddr8_en_2v5,
    .ddr8_en_1v2,
    .ddr8_en_0v6,
    .eth1_en_1v0,
    .eth1_en_1v0a,
    .eth1_en_2v5a,
    .eth1_en_3v3,
    .eth2_en_1v0,
    .eth2_en_1v0a,
    .eth2_en_2v5a,
    .eth2_en_3v3,
    .fpga_en_1v0,
    .fpga_en_1v0a,
    .fpga_en_1v25a,
    .fpga_en_1v8,
    .fpga_en_1v8_imx,
    .fpga_en_2v5a,
    .fpga_en_3v3_b4,
    .fpga_en_3v3_b5,
    .imx_en_1v1,
    .imx_en_1v8,
    .imx_en_2v9,
    .imx_en_3v3,
    .lvdt_en,
    .lvds_en,
    .step_down_en_2v2,
    .step_down_en_3v0,
    .step_down_en_4v0,
    .stepper_pri_en,
    .stepper_sec_en,
    .imx_nshort_1v1,
    .imx_nshort_1v8,
    .pf_status_to_pf,
    .step_down_status_to_pf,
    .ddr16_status_to_pf,
    .ddr8_status_to_pf,
    .stepper_pri_status_to_pf,
    .stepper_sec_status_to_pf,
    .lvdt_status_to_pf,
    .imx_status_to_pf,
    .lvds_status_to_pf,
    .eth2_status_to_pf,
    .eth1_status_to_pf,
    .pa3_status_to_pf,
    .rs422_ttl_farsight_to_bus_pa3,
    .rs422_ttl_bus_to_farsight_pa3,
    .rs422_ttl_farsight_to_bus_pf,
    .rs422_ttl_bus_to_farsight_pf,
    .fw_version,
    .debug,
    .heartbeat,
    .ddr8_failure_metadata,
    .ddr16_failure_metadata,
    .eth1_failure_metadata,
    .eth2_failure_metadata,
    .stepper_pri_failure_metadata,
    .stepper_sec_failure_metadata,
    .lvdt_failure_metadata,
    .imx_failure_metadata,
    .uart_tx_from_pa3              ( UART0_0_TX                          ),
    .tx_ready                      ( UART0_0_TXRDY                       ),
    .uart_wen                      ( health_monitor_io_0_uart_wen        ),
    .uart_csn                      ( health_monitor_io_0_uart_csn        ),
    .uart_bit8                     ( health_monitor_io_0_uart_bit8       ),
    .uart_oen                      ( health_monitor_io_0_uart_oen        ),
    .parity_en                     ( health_monitor_io_0_parity_en       ),
    .parity_oddneven               ( health_monitor_io_0_parity_oddneven ),
    .uart_rx                       ( health_monitor_io_0_uart_rx         ),
    .uart_tx_data                  ( health_monitor_io_0_uart_tx_data    ),
    .baud_val                      ( health_monitor_io_0_baud_val        )
);

//--------UART0
UART0 UART0_0(
    // Inputs
    .BIT8        ( health_monitor_io_0_uart_bit8 ),
    .CLK         ( clk ),
    .CSN         ( health_monitor_io_0_uart_csn ),
    .ODD_N_EVEN  ( health_monitor_io_0_parity_oddneven ),
    .OEN         ( health_monitor_io_0_uart_oen ),
    .PARITY_EN   ( health_monitor_io_0_parity_en ),
    .RESET_N     ( rstn ),
    .RX          ( health_monitor_io_0_uart_rx ),
    .WEN         ( health_monitor_io_0_uart_wen ),
    .BAUD_VAL    ( health_monitor_io_0_baud_val ),
    .DATA_IN     ( health_monitor_io_0_uart_tx_data ),
    // Outputs
    .OVERFLOW    (  ),
    .PARITY_ERR  (  ),
    .RXRDY       (  ),
    .TX          ( UART0_0_TX ),
    .TXRDY       ( UART0_0_TXRDY ),
    .FRAMING_ERR (  ),
    .DATA_OUT    (  ) 
);


endmodule
