"""Analyses as tests: each records its calculation and reports like a simulation.

An analysis item's evidence is "the recorded calculation". Here each analysis
is a test function that builds that record -- every input with the file and
line it was read from, then the working -- and asserts the item's criterion
on the result. The record goes where a simulation's result goes: into
`results/results-<module>.xml`, named as cocotb names its testcases (the
module stem as `classname`), so `make check` and `make coverage` read an
analysis exactly as they read a simulation; and into
`results/analysis/<module>.md`, the calculation as a document.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

from fsverif.design import Record

RESULTS = Path(__file__).resolve().parents[1] / "results"
_REPORTS = {}                      # module stem -> [(name, outcome, message, record)]


@pytest.fixture
def calc(request):
    """The analysis's record. Name the item and say what is being shown."""
    made = []

    def make(item: str, title: str) -> Record:
        r = Record(item, title)
        made.append(r)
        return r
    request.node._fsverif_records = made
    return make


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    report = outcome.get_result()
    if report.when == "call":
        records = getattr(item, "_fsverif_records", [])
        report.user_properties.append(("calculation", "\n".join(r.text() for r in records)))


def pytest_runtest_logreport(report):
    # Called for every test in the session; the simulations write their own
    # results, and only analyses are this file's to report.
    if not report.nodeid.startswith("analysis/"):
        return
    if report.when != "call" and not (report.when == "setup" and report.failed):
        return
    module = Path(report.nodeid.split("::")[0]).stem
    name = report.nodeid.split("::")[-1]
    record = dict(report.user_properties).get("calculation", "")
    message = None
    if report.failed:
        message = str(report.longrepr.reprcrash.message) if hasattr(report.longrepr, "reprcrash") \
            else str(report.longrepr)
    _REPORTS.setdefault(module, []).append(
        (name, "skipped" if report.skipped else "failed" if report.failed else "passed",
         message, record))


def pytest_sessionfinish(session):
    if hasattr(session.config, "workerinput"):
        return                      # the controller writes, once
    for module, cases in _REPORTS.items():
        suite = ET.Element("testsuite", name=module, tests=str(len(cases)))
        for name, outcome, message, record in cases:
            case = ET.SubElement(suite, "testcase", classname=module, name=name)
            if outcome == "failed":
                ET.SubElement(case, "failure", message=message or "").text = message
            elif outcome == "skipped":
                ET.SubElement(case, "skipped")
            ET.SubElement(case, "system-out").text = record
        RESULTS.mkdir(parents=True, exist_ok=True)
        root = ET.Element("testsuites")
        root.append(suite)
        ET.ElementTree(root).write(RESULTS / ("results-%s.xml" % module),
                                   encoding="utf-8", xml_declaration=True)
        md = RESULTS / "analysis" / ("%s.md" % module)
        md.parent.mkdir(parents=True, exist_ok=True)
        md.write_text("# %s\n\nGenerated by `verification/analysis/%s.py`.\n\n%s"
                      % (module, module, "\n".join(
                          "%s**%s: %s**\n\n%s" % ("", name, outcome.upper(), record)
                          for name, outcome, message, record in cases)))
