"""The hardware-version register, generated as the FPGA build generates it.

`ip/hw_version_ip/src/hw_version_apb_reg.sv` is not in the repository: the
build writes it from a template, stamping the version, the commit and the
build time in (`script/common/proj_util.tcl`). A test that compiled the copy a
previous FPGA build left in the source tree would fail in a clean checkout, and
in one with a build would test whatever that build stamped. So the tests run
the build's own Tcl into a directory of their own.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from fsverif.design import REPO

TEMPLATE = REPO / "ip" / "hw_version_ip" / "template" / "hw_version_apb_reg.sv.template"
PROJ_UTIL = REPO / "script" / "common" / "proj_util.tcl"


def head_commit() -> str:
    """The commit identifier exactly as synth.tcl derives it."""
    full = subprocess.run(["git", "rev-parse", "HEAD"], cwd=REPO, check=True,
                          capture_output=True, text=True).stdout.strip()
    return full[0:8]


def generate(out: Path, major: int, minor: int, fix: int, build: int,
             commit: str, time_utc: int) -> Path:
    """Run the build's generation procs into `out`; returns the generated source."""
    tclsh = shutil.which("tclsh")
    if not tclsh:
        raise RuntimeError("the hardware-version register is generated by the build's Tcl, "
                           "which needs tclsh on PATH (Debian/Ubuntu: the tcl package).")
    shutil.rmtree(out, ignore_errors=True)
    out.mkdir(parents=True)
    script = out / "generate.tcl"
    script.write_text(
        "source {%s}\n"
        "proj::copy_template -src_file {%s} -dest_folder {%s}\n"
        "proj::update_build_params -file_addr {%s} -hw_major %d -hw_minor %d "
        "-hw_fix %d -hw_build %d -git_hash %s -time_utc %d\n"
        % (PROJ_UTIL, TEMPLATE, out, out / "hw_version_apb_reg.sv", major, minor,
           fix, build, commit, time_utc))
    subprocess.run([tclsh, str(script)], check=True, capture_output=True, text=True)
    return out / "hw_version_apb_reg.sv"
