#ifndef CAM_FAULT_DETECTOR
#define CAM_FAULT_DETECTOR

// 'h0
#define CAM_FAULT_REG_OFFSET 0u
#define CAM_FAULT_OFFSET CAM_FAULT_REG_OFFSET
#define CAM_FAULT_MASK 0xFFFFFFFFu
#define CAM_FAULT_SHIFT 0u

// 'h1
#define CAM_FAULT_CLEAR_REG_OFFSET 4u
#define CAM_FAULT_CLEAR_OFFSET CAM_FAULT_CLEAR_REG_OFFSET
#define CAM_FAULT_CLEAR_MASK 0xFFFFFFFFu
#define CAM_FAULT_CLEAR_SHIFT 0u
#endif
