
#ifndef CAM_TRIG
#define CAM_TRIG

typedef enum
{
    XTRIG_LOW_TIME,
    FRAME_CAPTURE_TIME,
    FRAME_CAPTURE_AMOUNT,
    XTRIG_START,
    XTRIG_SRC_SEL,
    SCHEDULER_TIME_SEC,
    SCHEDULER_TIME_MSEC,
    CAM_TRIG_BUSY,
    CAM_TRIG_IRQ
}Cam_Trig_Reg_Index_t;

// 'h0
#define XTRIG_LOW_TIME_REG_OFFSET 0u
#define XTRIG_LOW_TIME_OFFSET XTRIG_LOW_TIME_REG_OFFSET
#define XTRIG_LOW_TIME_MASK 0xFFFFFFFFu
#define XTRIG_LOW_TIME_SHIFT 0u

// 'h1
#define FRAME_CAPTURE_TIME_REG_OFFSET 4u
#define FRAME_CAPTURE_TIME_OFFSET FRAME_CAPTURE_TIME_REG_OFFSET
#define FRAME_CAPTURE_TIME_MASK 0xFFFFFFFFu
#define FRAME_CAPTURE_TIME_SHIFT 0u

// 'h2
#define FRAME_CAPTURE_AMOUNT_REG_OFFSET 8u
#define FRAME_CAPTURE_AMOUNT_OFFSET FRAME_CAPTURE_AMOUNT_REG_OFFSET
#define FRAME_CAPTURE_AMOUNT_MASK 0xFFFFFFFFu
#define FRAME_CAPTURE_AMOUNT_SHIFT 0u

// 'h3
#define XTRIG_START_REG_OFFSET 12u
#define XTRIG_START_OFFSET START_REG_OFFSET
#define XTRIG_START_MASK 0xFFFFFFFFu
#define XTRIG_START_SHIFT 0u

// 'h4
#define XTRIG_SRC_SEL_REG_OFFSET 16u
#define XTRIG_SRC_SEL_OFFSET XTRIG_SRC_SEL_REG_OFFSET
#define XTRIG_SRC_SEL_MASK 0xFFFFFFFFu
#define XTRIG_SRC_SEL_SHIFT 0u

// 'h5
#define SCHEDULER_TIME_SEC_REG_OFFSET 20u
#define SCHEDULER_TIME_SEC_OFFSET SCHEDULER_TIME_SEC_REG_OFFSET
#define SCHEDULER_TIME_SEC_MASK 0xFFFFFFFFu
#define SCHEDULER_TIME_SEC_SHIFT 0u

// 'h6
#define SCHEDULER_TIME_MSEC_REG_OFFSET 24u
#define SCHEDULER_TIME_MSEC_OFFSET SCHEDULER_TIME_MSEC_REG_OFFSET
#define SCHEDULER_TIME_MSEC_MASK 0xFFFFFFFFu
#define SCHEDULER_TIME_MSEC_SHIFT 0u

// 'h7
#define CAM_TRIG_BUSY_REG_OFFSET 28u
#define CAM_TRIG_BUSY_OFFSET CAM_TRIG_BUSY_REG_OFFSET
#define CAM_TRIG_BUSY_MASK 0xFFFFFFFFu
#define CAM_TRIG_BUSY_SHIFT 0u

// 'h8
#define CAM_TRIG_IRQ_REG_OFFSET 32u
#define CAM_TRIG_IRQ_OFFSET CAM_TRIG_IRQ_REG_OFFSET
#define CAM_TRIG_IRQ_MASK 0xFFFFFFFFu
#define CAM_TRIG_IRQ_SHIFT 0u

#endif

