#ifndef IMAGE_METADATA
#define IMAGE_METADATA

// 'h0
#define METADATA_START_FLAG_REG_OFFSET 0u
#define METADATA_START_FLAG_OFFSET METADATA_START_FLAG_REG_OFFSET
#define METADATA_START_FLAG_MASK 0xFFFFFFFFu
#define METADATA_START_FLAG_SHIFT 0u

// 'h1
#define METADATA_SIZE_BYTES_REG_OFFSET 4u
#define METADATA_SIZE_BYTES_OFFSET METADATA_SIZE_BYTES_REG_OFFSET
#define METADATA_SIZE_BYTES_MASK 0xFFFFFFFFu
#define METADATA_SIZE_BYTES_SHIFT 0u

// 'h2
#define SENSOR_PXL_READOUT_FORMAT_REG_OFFSET 8u
#define SENSOR_PXL_READOUT_FORMAT_OFFSET SENSOR_PXL_READOUT_FORMAT_REG_OFFSET
#define SENSOR_PXL_READOUT_FORMAT_MASK 0xFFFFFFFFu
#define SENSOR_PXL_READOUT_FORMAT_SHIFT 0u

// 'h3
#define SENSOR_READ_DIR_REG_OFFSET 12u
#define SENSOR_READ_DIR_OFFSET SENSOR_READ_DIR_REG_OFFSET
#define SENSOR_READ_DIR_MASK 0xFFFFFFFFu
#define SENSOR_READ_DIR_SHIFT 0u

// 'h4
#define SENSOR_BIT_DEPTH_REG_OFFSET 16u
#define SENSOR_BIT_DEPTH_OFFSET SENSOR_BIT_DEPTH_REG_OFFSET
#define SENSOR_BIT_DEPTH_MASK 0xFFFFFFFFu
#define SENSOR_BIT_DEPTH_SHIFT 0u

// 'h5
#define SENSOR_GAIN_REG_OFFSET 20u
#define SENSOR_GAIN_OFFSET SENSOR_GAIN_REG_OFFSET
#define SENSOR_GAIN_MASK 0xFFFFFFFFu
#define SENSOR_GAIN_SHIFT 0u

// 'h6
#define SENSOR_BLO_REG_OFFSET 24u
#define SENSOR_BLO_OFFSET SENSOR_BLO_REG_OFFSET
#define SENSOR_BLO_MASK 0xFFFFFFFFu
#define SENSOR_BLO_SHIFT 0u

// 'h7
#define SENSOR_EXPO_USEC_REG_OFFSET 28u
#define SENSOR_EXPO_USEC_OFFSET SENSOR_EXPO_USEC_REG_OFFSET
#define SENSOR_EXPO_USEC_MASK 0xFFFFFFFFu
#define SENSOR_EXPO_USEC_SHIFT 0u

// 'h8
#define SENSOR_TRIG_MODE_REG_OFFSET 32u
#define SENSOR_TRIG_MODE_OFFSET SENSOR_TRIG_MODE_REG_OFFSET
#define SENSOR_TRIG_MODE_MASK 0xFFFFFFFFu
#define SENSOR_TRIG_MODE_SHIFT 0u

// 'h9
#define SENSOR_TEMP_RAW_REG_OFFSET 36u
#define SENSOR_TEMP_RAW_OFFSET SENSOR_TEMP_RAW_REG_OFFSET
#define SENSOR_TEMP_RAW_MASK 0xFFFFFFFFu
#define SENSOR_TEMP_RAW_SHIFT 0u

// 'hA
#define BUFF_WRITE_INDEX_REG_OFFSET 40u
#define BUFF_WRITE_INDEX_OFFSET BUFF_WRITE_INDEX_REG_OFFSET
#define BUFF_WRITE_INDEX_MASK 0xFFFFFFFFu
#define BUFF_WRITE_INDEX_SHIFT 0u

// 'hB
#define FOCUS_REQ_DIST_M_REG_OFFSET 44u
#define FOCUS_REQ_DIST_M_OFFSET FOCUS_REQ_DIST_M_REG_OFFSET
#define FOCUS_REQ_DIST_M_MASK 0xFFFFFFFFu
#define FOCUS_REQ_DIST_M_SHIFT 0u

// 'hC
#define FOCUS_COMP_DIST_M_REG_OFFSET 48u
#define FOCUS_COMP_DIST_M_OFFSET FOCUS_COMP_DIST_M_REG_OFFSET
#define FOCUS_COMP_DIST_M_MASK 0xFFFFFFFFu
#define FOCUS_COMP_DIST_M_SHIFT 0u

// 'hD
#define FOCUS_LVDT_POS_NM_REG_OFFSET 52u
#define FOCUS_LVDT_POS_NM_OFFSET FOCUS_LVDT_POS_NM_REG_OFFSET
#define FOCUS_LVDT_POS_NM_MASK 0xFFFFFFFFu
#define FOCUS_LVDT_POS_NM_SHIFT 0u

// 'hE
#define TIMESTAMP_UNIX_EPOCH_SEC_REG_OFFSET 56u
#define TIMESTAMP_UNIX_EPOCH_SEC_OFFSET TIMESTAMP_UNIX_EPOCH_SEC_REG_OFFSET
#define TIMESTAMP_UNIX_EPOCH_SEC_MASK 0xFFFFFFFFu
#define TIMESTAMP_UNIX_EPOCH_SEC_SHIFT 0u

// 'hF
#define TIMESTAMP_SUBSEC_NSEC_REG_OFFSET 60u
#define TIMESTAMP_SUBSEC_NSEC_OFFSET TIMESTAMP_SUBSEC_NSEC_REG_OFFSET
#define TIMESTAMP_SUBSEC_NSEC_MASK 0xFFFFFFFFu
#define TIMESTAMP_SUBSEC_NSEC_SHIFT 0u

// 'h10
#define VERSION_REG_OFFSET 64u
#define VERSION_OFFSET VERSION_REG_OFFSET
#define VERSION_MASK 0xFFFFFFFFu
#define VERSION_SHIFT 0u

// 'h11
#define RESERVED_PADDING0_REG_OFFSET 68u
#define RESERVED_PADDING0_OFFSET RESERVED_PADDING0_REG_OFFSET
#define RESERVED_PADDING0_MASK 0xFFFFFFFFu
#define RESERVED_PADDING0_SHIFT 0u

// 'h12
#define RESERVED_PADDING1_REG_OFFSET 72u
#define RESERVED_PADDING1_OFFSET RESERVED_PADDING1_REG_OFFSET
#define RESERVED_PADDING1_MASK 0xFFFFFFFFu
#define RESERVED_PADDING1_SHIFT 0u

// 'h13
#define METADATA_CRC32_REG_OFFSET 76u
#define METADATA_CRC32_OFFSET METADATA_CRC32_REG_OFFSET
#define METADATA_CRC32_MASK 0xFFFFFFFFu
#define METADATA_CRC32_SHIFT 0u

#endif