"""DDR4 write bandwidth, at the DMA boundary: PF-DMAW-10.

Item: VC-PF-0039. Clause: VVP-PF-001.

  PF-DMAW-10  Each DDR4 bank shall sustain 17.4 Gbit/s sustained image write
              bandwidth while it is the selected write destination, without
              frame loss.

**What this shows, and what it does not.** The DUTs are
`dma_write_ddr4_8gb_hier` and `dma_write_ddr4_16gb_hier`, generated by `make
ip` byte-identical to the build's: the write DMA, its COREFIFO pixel-to-DDR
clock crossing, and its register block. Beyond them is an **ideal arbiter**,
acknowledging every request at once and taking a beat every clock. So this
shows the DMA path -- line capture, width conversion, the clock crossing and
the burst engine -- sustains the rate at its real clocks, without loss or
duplication. It does **not** show the DDR4 controller and memory do: PF_DDR4
is encrypted, and its efficiency under refresh and turnaround is the
analysis item's (VC-PF-0038) and hardware's to establish. The item permits
exactly this, "an explicitly scoped boundary model".

**The stream is the camera's line timing.** 70 FPS x 4581 lines is a line
every 3.1185 us. A line is 144 beats of 384 bits on the 79.2 MHz pixel clock
-- 6912 bytes, a whole number of the width converter's four-beat groups and
more than the 6784 bytes of a real line -- so the rate offered is 17.73
Gbit/s, above the requirement's 17.4. `H_SIZE_BYTE` is set to 6912 so lines
do not overlap in memory.

**A steady-state window, not a frame.** The COREFIFO simulates at about 97 s
per simulated millisecond, so a whole 14.3 ms frame is 23 minutes a bank.
The window is 200 lines, 624 us, then the frame closes. A path that could not
keep up would fall behind by a fixed amount per line and fill its FIFO within
it; the test also reports the worst lag between a line arriving and its
burst completing, which is the margin.

**Every byte is checked.** Each 32-bit word of the camera stream carries its
own index; the arbiter model records every beat written and its address. The
bytes written must be the bytes sent, in order, each line at `H_SIZE_BYTE`
from the last -- nothing dropped, nothing written twice.

**Clocks are the build's**: pixel 79.2 MHz (`PF_CCC_C1`), APB 50 MHz, and each
bank's PF_DDR4 user clock -- 150 MHz for the 8GB bank, 137.5 MHz for the 16GB
(`PF-F-28`).
"""

from __future__ import annotations

import cocotb
from cocotb.triggers import ClockCycles, FallingEdge, ReadOnly, RisingEdge, Timer
from cocotb.utils import get_sim_time

from fsverif import sim
from fsverif.bfm.apb import Apb
from fsverif.clkrst import start_clock

BANKS = {
    # bank: (DUT, clock, reset, real MHz, simulated period ns, DDR data width)
    "8gb": ("dma_write_ddr4_8gb_hier", "ddr4_8gb_clk", "ddr4_8gb_rst_n",
            150.0, 6.666, 256),
    "16gb": ("dma_write_ddr4_16gb_hier", "ddr4_16gb_clk", "ddr4_16gb_rst_n",
             137.5, 7.272, 512),
}
PIXEL_NS, APB_NS = 12.626, 20
LINE_PERIOD_NS = 1e9 / (70 * 4581)            # 3118.5 ns
BEATS_PER_LINE = 144                          # x 48 bytes = 6912 bytes
LINE_BYTES = BEATS_PER_LINE * 48
LINES = 200
REQUIRED_GBPS = 17.4
H_SIZE_BYTE, FRAME_INDEX = 0x04, 0x08
FRAME_WIDTH = 25                              # address bits per frame


def _now_ns() -> float:
    return get_sim_time("ns")


def _beat(line: int, beat: int) -> int:
    """Twelve 32-bit words, each its own index in the frame's stream."""
    base = (line * BEATS_PER_LINE + beat) * 12
    value = 0
    for w in range(12):
        value |= ((base + w) & 0xFFFF_FFFF) << (32 * w)
    return value


@cocotb.test()
async def test_PF_DMAW_10_17_4g_write_without_loss(dut):
    """VC-PF-0039: 17.4 Gbit/s sustained into each bank's DMA, byte-exact."""
    bank = "16gb" if hasattr(dut, "ddr4_16gb_clk") else "8gb"
    _, clk_name, rst_name, mhz, period, width = BANKS[bank]
    ddr, ddr_rst = getattr(dut, clk_name), getattr(dut, rst_name)
    start_clock(ddr, period)
    start_clock(dut.pixel_clk, PIXEL_NS)
    start_clock(dut.pclk, APB_NS)
    apb = Apb(dut, dut.pclk, "s_apb_")
    for s in ("cam_frame_valid", "cam_line_valid", "cam_data_in",
              "arb_write_ack", "arb_write_done"):
        getattr(dut, s).value = 0
    # Reset as a falling edge, not a 0 from time zero: the COREFIFO's
    # asynchronous reset acts on the edge, and a four-state simulator starts
    # the net at X, not 0.
    for r in (ddr_rst, dut.pixel_rst_n, dut.presetn):
        r.value = 1
    await ClockCycles(dut.pclk, 2)
    for r in (ddr_rst, dut.pixel_rst_n, dut.presetn):
        r.value = 0
    await ClockCycles(dut.pclk, 10)
    for r in (ddr_rst, dut.pixel_rst_n, dut.presetn):
        r.value = 1
    await ClockCycles(dut.pclk, 10)
    await apb.write(H_SIZE_BYTE, LINE_BYTES)
    await ClockCycles(dut.pclk, 20)

    bursts = []             # (start address, [words], time the burst completed)
    line_ends = []          # time each line's last beat was driven

    async def arbiter():
        """Ideal: acknowledge at once, a beat every clock, done at the last."""
        while True:
            await RisingEdge(dut.arb_write_req)
            await RisingEdge(ddr)
            await ReadOnly()
            addr = int(dut.arb_write_start_addr.value)
            beats = int(dut.arb_write_burst_len.value) + 1
            await FallingEdge(ddr)
            dut.arb_write_ack.value = 1
            await FallingEdge(ddr)
            dut.arb_write_ack.value = 0
            words = []
            while len(words) < beats:
                # Mid-cycle, not in the edge's read-only phase: the COREFIFO's
                # RAM models drive their data 1 ns after the clock (`#1`), and
                # an edge sample would read the previous word against the new
                # data-valid. What the falling edge sees is what the next
                # rising edge -- a real arbiter -- captures.
                await FallingEdge(ddr)
                if int(dut.arb_write_valid.value):
                    words.append(int(dut.arb_write_data.value))
            dut.arb_write_done.value = 1
            await FallingEdge(ddr)
            dut.arb_write_done.value = 0
            bursts.append((addr, words, _now_ns()))

    cocotb.start_soon(arbiter())

    # The frame: 200 lines on the camera's line period.
    await FallingEdge(dut.pixel_clk)
    dut.cam_frame_valid.value = 1
    await ClockCycles(dut.pixel_clk, 50, rising=False)
    t0 = _now_ns()
    for line in range(LINES):
        for beat in range(BEATS_PER_LINE):
            dut.cam_line_valid.value = 1
            dut.cam_data_in.value = _beat(line, beat)
            await FallingEdge(dut.pixel_clk)
        dut.cam_line_valid.value = 0
        dut.cam_data_in.value = 0
        line_ends.append(_now_ns())
        next_start = t0 + (line + 1) * LINE_PERIOD_NS
        wait = next_start - _now_ns()
        if wait > PIXEL_NS:
            await Timer(round(wait / PIXEL_NS) * PIXEL_NS, unit="ns",
                        round_mode="round")
            await FallingEdge(dut.pixel_clk)
    elapsed = _now_ns() - t0
    await ClockCycles(dut.pixel_clk, 400, rising=False)
    dut.cam_frame_valid.value = 0
    await ClockCycles(dut.pixel_clk, 400)
    frame_index = (await apb.read(FRAME_INDEX)).data

    offered = LINES * LINE_BYTES * 8 / elapsed          # bits per ns = Gbit/s
    problems = []

    # Every byte, in order, each line at its address.
    per_line = {}
    for addr, words, done in bursts:
        offset = addr & ((1 << FRAME_WIDTH) - 1)
        line, within = divmod(offset, LINE_BYTES)
        per_line.setdefault(line, []).append((within, words, done))
    wrong = []
    lags = []
    for line in range(LINES):
        sent = 0
        for beat in range(BEATS_PER_LINE):
            sent |= _beat(line, beat) << (384 * beat)
        chunks = sorted(per_line.get(line, []), key=lambda c: c[0])
        got, position = 0, 0
        for within, words, done in chunks:
            if within * 8 != position:
                wrong.append("line %d: a burst at byte %d where %d was expected"
                             % (line, within, position // 8))
            for w in words:
                got |= w << position
                position += width
        if position < LINE_BYTES * 8 or got & ((1 << (LINE_BYTES * 8)) - 1) != sent:
            wrong.append("line %d: %d of %d bytes written%s"
                         % (line, position // 8, LINE_BYTES,
                            "" if position < LINE_BYTES * 8 else ", and they differ"))
        if position > LINE_BYTES * 8 and got >> (LINE_BYTES * 8):
            wrong.append("line %d: %d bytes beyond the line written"
                         % (line, position // 8 - LINE_BYTES))
        if chunks:
            lags.append(max(c[2] for c in chunks) - line_ends[line])
    stray = sorted(set(per_line) - set(range(LINES)))
    if stray:
        wrong.append("bursts at lines %s, which were never sent" % stray[:5])

    worst = max(lags) if lags else float("nan")
    dut._log.info(
        "%s bank at %.1f MHz: %d lines of %d bytes offered at %.2f Gbit/s; %d "
        "bursts written; worst line-end-to-write-done %.0f ns of the %.0f ns "
        "line period; frame index after the frame %d", bank, mhz, LINES,
        LINE_BYTES, offered, len(bursts), worst, LINE_PERIOD_NS, frame_index)
    if offered < REQUIRED_GBPS:
        problems.append("the stream offered %.2f Gbit/s, below the %.1f the test "
                        "must apply" % (offered, REQUIRED_GBPS))
    problems += wrong[:10]
    if len(wrong) > 10:
        problems.append("... and %d more" % (len(wrong) - 10))
    if lags and worst >= LINE_PERIOD_NS:
        problems.append("a line's write completed %.0f ns after it arrived, more "
                        "than a line period: the path is falling behind" % worst)
    if frame_index != 0:
        problems.append("FRAME_INDEX reads %d after the first frame, not 0"
                        % frame_index)
    assert not problems, "\n  ".join(["PF-DMAW-10 (%s):" % bank] + problems)


def _run(bank: str) -> None:
    top = BANKS[bank][0]
    sim.run(hdl_toplevel=top,
            sources=(sim.block("dma_write_ip", "dma_write_apb_reg.sv",
                               "dma_write_apb_reg_ddr4_%s.sv" % bank,
                               "wconv_4in_3out.sv", "dma_write_recv_ctrl.sv",
                               "dma_write_send_ctrl.sv", "dma_write_ctrl.sv",
                               "dma_write_ddr4_%s.sv" % bank)
                     + sim.vendor("COREFIFO_DMA_WR_%s" % bank.upper(), top)
                     + [sim.polarfire_source()]),
            test_module="test_pf_dmaw_rate", run_id="test_pf_dmaw_rate.%s" % bank)


def test_pf_dmaw_10_8gb():
    _run("8gb")


def test_pf_dmaw_10_16gb():
    _run("16gb")
