"""HK-SRC-02: every power source enable is deasserted after reset release.

Item: VC-HK-0033. Clause: VVP-HK-004.

  Following release of reset, every power source enable shall be deasserted,
  regardless of the state the source was in when reset was asserted.

The criterion in the item is what this has to establish, and the second half
of the sentence is the whole test. A device that simply powers up with its
enables low satisfies the first half by doing nothing. What the requirement
asks is that the *previous state does not survive* -- so the test drives the
device into a state where enables are asserted, asserts reset from there, and
checks what comes out.

Everything here is at the pin boundary. The requirement is about outputs the
board can see, so observing anything inside the design would be verifying a
different claim than the one written down.
"""

from __future__ import annotations

import cocotb

from fsverif import boot, sim
from fsverif.boot import FILTER_CYCLES, asserted
from fsverif.clkrst import advance, until
from fsverif.pins import CONTROL_INPUTS, POWER_ENABLES, RESET_N

# The flight value. `VENV-02` requires the environment to exercise the design
# at its synthesis parameter values, and this is the parameter that hid
# HK-F-01: at the development value of 3 the boot timeout is reachable, at the
# flight value of 50 it is not, and every test passed anyway.
WAIT_TIME_MULT_FACTOR = 50
PULSE_WIDTH = 250


def _request(dut, requested: int, *, except_for: tuple = ()) -> None:
    """Ask for, or stand down, every software-controlled region.

    The power-good and fault inputs are not set here. They are driven by the
    board model, which brings each rail up a datasheet delay after the device
    enables it. Holding them at a constant level -- which is what this test
    did first -- reached one enable of thirty-three, because every region of
    the sequence waits for a rising edge that a constant never produces.

    `except_for` exists because the two stepper drivers are a redundant pair:
    `health_monitor.sv:547` powers the secondary down whenever the primary has
    booted, so no instant has all thirty-three enables high and a test that
    waits for one waits forever. Covering both means asking twice.

    The control inputs are the same trap one level up. `health_monitor.sv:591`
    starts a software region on `{ctrl_r1, ctrl} == 2'b01` and only once the
    FPGA region has booted, so a test that holds them high from time zero
    spends its rising edge before the device can act on it and never brings up
    any of the fifteen software-controlled enables.
    """
    for name in CONTROL_INPUTS:
        getattr(dut, name).value = 0 if name in except_for else requested


@cocotb.test()
async def test_HK_SRC_02_enables_low_after_reset(dut):
    """Assert reset from a state where enables are high, twice over.

    Twice because the requirement is about *every* power source enable, and
    the two stepper drivers are mutually exclusive: the secondary is held down
    while the primary is up. One pass selects the primary, the other the
    secondary, and between them every enable is driven high and then reset.
    """
    reset_n = getattr(dut, RESET_N)
    covered = set()

    for selection, stood_down in (("primary", ("stepper_sec_ctrl",)),
                                  ("secondary", ("stepper_pri_ctrl",))):
        expected = [n for n in POWER_ENABLES
                    if n != ("stepper_sec_en" if selection == "primary"
                             else "stepper_pri_en")]

        # Bring the device up from reset with nothing requested, and let the
        # hardware-controlled regions boot on their own. HK-SEQ-01 holds the
        # sequence off for 1 s after reset release; the clock is generated by
        # the wrapper rather than by cocotb, because driving it from Python
        # costs a callback on each of those hundred million edges.
        await boot.hardware(dut)

        # Only now request the software-controlled regions, which is the order
        # the PolarFire works in.
        _request(dut, 1, except_for=stood_down)
        waited = await until(
            dut.clk, lambda: not [n for n in expected if n not in asserted(dut)],
            timeout_s=2.0,
            describe=lambda: "still low: %s" % ", ".join(
                n for n in expected if n not in asserted(dut)))
        dut._log.info("%s stepper selected: %d enables up, %.3f s after the "
                      "request", selection, len(asserted(dut)), waited)

        before = asserted(dut)
        covered |= set(before)

        # The requirement: assert reset from that state and release it.
        reset_n.value = 0
        await advance(dut.clk, cycles=FILTER_CYCLES)
        reset_n.value = 1
        await advance(dut.clk, cycles=FILTER_CYCLES)

        still_high = asserted(dut)
        assert not still_high, (
            "with the %s stepper selected, these power enables were still "
            "asserted after reset release, so the state the source was in "
            "when reset was asserted survived it: %s"
            % (selection, ", ".join(still_high)))

    # Every enable, not merely the ones a single pass happened to raise.
    # "At least one" was what this asserted before the board model existed,
    # and it passed while thirty-two of the thirty-three never moved.
    never = [n for n in POWER_ENABLES if n not in covered]
    assert not never, (
        "these power enables were never asserted in either pass, so nothing "
        "here shows that reset clears them -- which is a defect in the "
        "stimulus and not a pass: %s" % ", ".join(never))


def test_hk_src_02():
    """Build and run the device, at its synthesis parameter values."""
    sim.run_device(
        test_module="test_hk_src_02",
        parameters={"WAIT_TIME_MULT_FACTOR": WAIT_TIME_MULT_FACTOR,
                    "PULSE_WIDTH": PULSE_WIDTH},
    )
