#ifndef CAM_MUX
#define CAM_MUX

// 'h0
#define MUX_CLEAR_REG_OFFSET 0u
#define MUX_CLEAR_OFFSET MUX_CLEAR_REG_OFFSET
#define MUX_CLEAR_MASK 0xFFFFFFFFu
#define MUX_CLEAR_SHIFT 0u

// 'h1
#define MUX_ENABLE_REG_OFFSET 4u
#define MUX_ENABLE_OFFSET MUX_ENABLE_REG_OFFSET
#define MUX_ENABLE_MASK 0xFFFFFFFFu
#define MUX_ENABLE_SHIFT 0u

// 'h2
#define MUX_SELECT_REG_OFFSET 8u
#define MUX_SELECT_OFFSET MUX_SELECT_REG_OFFSET
#define MUX_SELECT_MASK 0xFFFFFFFFu
#define MUX_SELECT_SHIFT 0u

// 'h3
#define DDR4_16GB_FULL_REG_OFFSET 12u
#define DDR4_16GB_FULL_OFFSET DDR4_16GB_FULL_REG_OFFSET
#define DDR4_16GB_FULL_MASK 0xFFFFFFFFu
#define DDR4_16GB_FULL_SHIFT 0u

// 'h4
#define DDR4_8GB_FULL_REG_OFFSET 16u
#define DDR4_8GB_FULL_OFFSET DDR4_8GB_FULL_REG_OFFSET
#define DDR4_8GB_FULL_MASK 0xFFFFFFFFu
#define DDR4_8GB_FULL_SHIFT 0u
#endif
