#ifndef DMA_READ_CTRL_REG_H
#define DMA_READ_CTRL_REG_H
//------------------------------------------------------------------------------
// UDP TO DMA Controller registers
//------------------------------------------------------------------------------
// 'h0
#define CLEAR_DMA_READ_CTRL_REG_OFFSET 0u
#define CLEAR_DMA_READ_CTRL_OFFSET CLEAR_REG_OFFSET
#define CLEAR_DMA_READ_CTRL_MASK 0xFFFFFFFFu
#define CLEAR_DMA_READ_CTRL_SHIFT 0u
// 'h1
#define DMA_READ_FRAME_INDEX_REG_OFFSET 4u
#define DMA_READ_FRAME_INDEX_OFFSET DMA_READ_FRAME_INDEX_REG_OFFSET
#define DMA_READ_FRAME_INDEX_MASK 0xFFFFFFFFu
#define DMA_READ_FRAME_INDEX_SHIFT 0u
// 'h2
#define FRAME_READ_DONE_COUNT_REG_OFFSET 8u
#define FRAME_READ_DONE_COUNT_OFFSET FRAME_READ_DONE_COUNT_REG_OFFSET
#define FRAME_READ_DONE_COUNT_MASK 0xFFFFFFFFu
#define FRAME_READ_DONE_COUNT_SHIFT 0u
// 'h3
#define FRAME_READ_REQ_REG_OFFSET 12u
#define FRAME_READ_REQ_OFFSET FRAME_READ_REQ_REG_OFFSET
#define FRAME_READ_REQ_MASK 0xFFFFFFFFu
#define FRAME_READ_REQ_SHIFT 0u
// 'h4
#define H_SIZE_BEAT_REG_OFFSET 16u
#define H_SIZE_BEAT_OFFSET H_SIZE_BEAT_REG_OFFSET
#define H_SIZE_BEAT_MASK 0xFFFFFFFFu
#define H_SIZE_BEAT_SHIFT 0u
// 'h5
#define H_SIZE_BYTE_REG_OFFSET 20u
#define H_SIZE_BYTE_OFFSET H_SIZE_BYTE_REG_OFFSET
#define H_SIZE_BYTE_MASK 0xFFFFFFFFu
#define H_SIZE_BYTE_SHIFT 0u
// 'h6
#define JUMBO_EN_REG_OFFSET 24u
#define JUMBO_EN_OFFSET JUMBO_EN_REG_OFFSET
#define JUMBO_EN_MASK 0xFFFFFFFFu
#define JUMBO_EN_SHIFT 0u
// 'h7
#define V_SIZE_LINE_REG_OFFSET 28u
#define V_SIZE_LINE_OFFSET V_SIZE_LINE_REG_OFFSET
#define V_SIZE_LINE_MASK 0xFFFFFFFFu
#define V_SIZE_LINE_SHIFT 0u
// 'h8
#define DMA_TIMEOUT_ERR_REG_OFFSET 32u
#define DMA_TIMEOUT_ERR_OFFSET DMA_TIMEOUT_ERR_REG_OFFSET
#define DMA_TIMEOUT_ERR_MASK 0xFFFFFFFFu
#define DMA_TIMEOUT_ERR_SHIFT 0u
// 'h9
#define PYL_ACPT_ERR_REG_OFFSET 36u
#define PYL_ACPT_ERR_OFFSET PYL_ACPT_ERR_REG_OFFSET
#define PYL_ACPT_ERR_MASK 0xFFFFFFFFu
#define PYL_ACPT_ERR_SHIFT 0u
// 'hA
#define SEND_LAST_ERR_REG_OFFSET 40u
#define SEND_LAST_ERR_OFFSET SEND_LAST_ERR_REG_OFFSET
#define SEND_LAST_ERR_MASK 0xFFFFFFFFu
#define SEND_LAST_ERR_SHIFT 0u
// 'hB
#define SEND_PYL_ERR_REG_OFFSET 44u
#define SEND_PYL_ERR_OFFSET SEND_PYL_ERR_REG_OFFSET
#define SEND_PYL_ERR_MASK 0xFFFFFFFFu
#define SEND_PYL_ERR_SHIFT 0u
// 'hC
#define SOF_REQ_ERR_REG_OFFSET 48u
#define SOF_REQ_ERR_OFFSET SOF_REQ_ERR_REG_OFFSET
#define SOF_REQ_ERR_MASK 0xFFFFFFFFu
#define SOF_REQ_ERR_SHIFT 0u
// 'hD
#define WAIT_ACK_ERR_REG_OFFSET 52u
#define WAIT_ACK_ERR_OFFSET WAIT_ACK_ERR_REG_OFFSET
#define WAIT_ACK_ERR_MASK 0xFFFFFFFFu
#define WAIT_ACK_ERR_SHIFT 0u
// 'hE
#define FRAME_XFER_TIMEOUT_ERR_REG_OFFSET 56u
#define FRAME_XFER_TIMEOUT_ERR_OFFSET FRAME_XFER_TIMEOUT_ERR_REG_OFFSET
#define FRAME_XFER_TIMEOUT_ERR_MASK 0xFFFFFFFFu
#define FRAME_XFER_TIMEOUT_ERR_SHIFT 0u
// 'hF
#define RESET_DONE_COUNTER_REG_OFFSET 60u
#define RESET_DONE_COUNTER_OFFSET RESET_DONE_COUNTER_REG_OFFSET
#define RESET_DONE_COUNTER_MASK 0xFFFFFFFFu
#define RESET_DONE_COUNTER_SHIFT 0u
// 'h10
#define UDP_METADATA_SEL_REG_OFFSET 64u
#define UDP_METADATA_SEL_OFFSET UDP_METADATA_SEL_REG_OFFSET
#define UDP_METADATA_SEL_MASK 0xFFFFFFFFu
#define UDP_METADATA_SEL_SHIFT 0u
// 'h11
#define FRAME_READ_DONE_IRQ_REG_OFFSET 68u
#define FRAME_READ_DONE_IRQ_OFFSET FRAME_READ_DONE_IRQ_REG_OFFSET
#define FRAME_READ_DONE_IRQ_MASK 0xFFFFFFFFu
#define FRAME_READ_DONE_IRQ_SHIFT 0u
// 'h12..'h25 - Metadata data words (RO) 20 x 32-bit = 640 bits
#define METADATA_DATA_BASE_REG_OFFSET 72u
#define METADATA_WORD_COUNT 20u
#define METADATA_DATA_REG_OFFSET(n) (METADATA_DATA_BASE_REG_OFFSET + ((n) * 4u))

#endif
