#ifndef DMA_WRITE_REG_H
#define DMA_WRITE_REG_H

//------------------------------------------------------------------------------
// DMA Write Registers
//------------------------------------------------------------------------------
// 'h0
#define CLEAR_INDEX_REG_OFFSET 0u
#define CLEAR_INDEX_OFFSET CLEAR_INDEX_REG_OFFSET
#define CLEAR_INDEX_MASK 0xFFFFFFFFu
#define CLEAR_INDEX_SHIFT 0u
// 'h1
#define DMA_WRITE_H_SIZE_BYTE_REG_OFFSET 4u
#define DMA_WRITE_H_SIZE_BYTE_OFFSET DMA_WRITE_H_SIZE_BYTE_REG_OFFSET
#define DMA_WRITE_H_SIZE_BYTE_MASK 0xFFFFFFFFu
#define DMA_WRITE_H_SIZE_BYTE_SHIFT 0u
// 'h2
#define DMA_WRITE_FRAME_INDEX_REG_OFFSET 8u
#define DMA_WRITE_FRAME_INDEX_OFFSET DMA_WRITE_FRAME_INDEX_REG_OFFSET
#define DMA_WRITE_FRAME_INDEX_MASK 0xFFFFFFFFu
#define DMA_WRITE_FRAME_INDEX_SHIFT 0u
// 'h3
#define CORE_READY_REG_OFFSET 12u
#define CORE_READY_OFFSET CORE_READY_REG_OFFSET
#define CORE_READY_MASK 0xFFFFFFFFu
#define CORE_READY_SHIFT 0u
// 'h4
#define FRAME_WRITE_DONE_REG_OFFSET 16u
#define FRAME_WRITE_DONE_OFFSET FRAME_WRITE_DONE_REG_OFFSET
#define FRAME_WRITE_DONE_MASK 0xFFFFFFFFu
#define FRAME_WRITE_DONE_SHIFT 0u
// 'h5
#define TIMEOUT_ERR_REG_OFFSET 20u
#define TIMEOUT_ERR_OFFSET TIMEOUT_ERR_REG_OFFSET
#define TIMEOUT_ERR_MASK 0xFFFFFFFFu
#define TIMEOUT_ERR_SHIFT 0u

#endif
