#ifndef HW_VERSION
#define HW_VERSION

// 'h0
#define BUILD_VERSION_REG_OFFSET 0u
#define BUILD_VERSION_OFFSET BUILD_VERSION_REG_OFFSET
#define BUILD_VERSION_MASK 0xFFFFFFFFu
#define BUILD_VERSION_SHIFT 0u

// 'h1
#define BUILD_GIT_HASH_REG_OFFSET 4u
#define BUILD_GIT_HASH_OFFSET BUILD_GIT_HASH_REG_OFFSET
#define BUILD_GIT_HASH_MASK 0xFFFFFFFFu
#define BUILD_GIT_HASH_SHIFT 0u

// 'h2
#define BUILD_TIME_UTC_SEC_REG_OFFSET 8u
#define BUILD_TIME_UTC_SEC_OFFSET BUILD_TIME_UTC_SEC_REG_OFFSET
#define BUILD_TIME_UTC_SEC_MASK 0xFFFFFFFFu
#define BUILD_TIME_UTC_SEC_SHIFT 0u
#endif
