#ifndef PPS
#define PPS

// 'h0
#define TRIGGER_TIME_JAM_REG_OFFSET 0u
#define TRIGGER_TIME_JAM_OFFSET TRIGGER_TIME_JAM_REG_OFFSET
#define TRIGGER_TIME_JAM_MASK 0xFFFFFFFFu
#define TRIGGER_TIME_JAM_SHIFT 0u

// 'h1
#define LOAD_SECONDS_REG_OFFSET 4u
#define LOAD_SECONDS_OFFSET LOAD_SECONDS_REG_OFFSET
#define LOAD_SECONDS_MASK 0xFFFFFFFFu
#define LOAD_SECONDS_SHIFT 0u

// 'h2
#define PPS_RX_DELAY_REG_OFFSET 8u
#define PPS_RX_DELAY_OFFSET PPS_RX_DELAY_REG_OFFSET
#define PPS_RX_DELAY_MASK 0xFFFFFFFFu
#define PPS_RX_DELAY_SHIFT 0u

// 'h3
#define EN_LOCAL_PPS_SOURCE_REG_OFFSET 12u
#define EN_LOCAL_PPS_SOURCE_OFFSET EN_LOCAL_PPS_SOURCE_REG_OFFSET
#define EN_LOCAL_PPS_SOURCE_MASK 0xFFFFFFFFu
#define EN_LOCAL_PPS_SOURCE_SHIFT 0u

// 'h4
#define FREQUENCY_ERROR_REG_OFFSET 16u
#define FREQUENCY_ERROR_OFFSET FREQUENCY_ERROR_REG_OFFSET
#define FREQUENCY_ERROR_MASK 0xFFFFFFFFu
#define FREQUENCY_ERROR_SHIFT 0u

// 'h5
#define PHASE_ERROR_REG_OFFSET 20u
#define PHASE_ERROR_OFFSET PHASE_ERROR_REG_OFFSET
#define PHASE_ERROR_MASK 0xFFFFFFFFu
#define PHASE_ERROR_SHIFT 0u

// 'h6
#define SECONDS_REG_OFFSET 24u
#define SECONDS_OFFSET SECONDS_REG_OFFSET
#define SECONDS_MASK 0xFFFFFFFFu
#define SECONDS_SHIFT 0u

// 'h7
#define NANOSECONDS_REG_OFFSET 28u
#define NANOSECONDS_OFFSET NANOSECONDS_REG_OFFSET
#define NANOSECONDS_MASK 0xFFFFFFFFu
#define NANOSECONDS_SHIFT 0u

// 'h8
#define CLEAR_IRQ_REG_OFFSET 32u
#define CLEAR_IRQ_OFFSET CLEAR_IRQ_REG_OFFSET
#define CLEAR_IRQ_MASK 0xFFFFFFFFu
#define CLEAR_IRQ_SHIFT 0u

#endif
