#ifndef TIMER
#define TIMER

// 'h0
#define TIMER_LOAD_REG_OFFSET 0u
#define TIMER_LOAD_OFFSET TIMER_LOAD_REG_OFFSET
#define TIMER_LOAD_MASK 0xFFFFFFFFu
#define TIMER_LOAD_SHIFT 0u

// 'h1
#define TIMER_VALUE_REG_OFFSET 4u
#define TIMER_VALUE_OFFSET TIMER_VALUE_REG_OFFSET
#define TIMER_VALUE_MASK 0xFFFFFFFFu
#define TIMER_VALUE_SHIFT 0u

// 'h2
#define TIMER_CONTROL_REG_OFFSET 8u
#define TIMER_CONTROL_OFFSET TIMER_CONTROL_REG_OFFSET
#define TIMER_CONTROL_MASK 0xFFFFFFFFu
#define TIMER_CONTROL_SHIFT 0u

// 'h3
#define TIMER_ENABLE_REG_OFFSET 8u
#define TIMER_ENABLE_OFFSET TIMER_ENABLE_REG_OFFSET
#define TIMER_ENABLE_MASK 0xFFFFFFFFu
#define TIMER_ENABLE_SHIFT 0u

// 'h4
#define TIMER_MODE_REG_OFFSET 8u
#define TIMER_MODE_OFFSET TIMER_MODE_REG_OFFSET
#define TIMER_MODE_MASK 0xFFFFFFFFu
#define TIMER_MODE_SHIFT 1u

// 'h5
#define TIMER_INT_ENABLE_REG_OFFSET 8u
#define TIMER_INT_ENABLE_OFFSET TIMER_INT_ENABLE_REG_OFFSET
#define TIMER_INT_ENABLE_MASK 0xFFFFFFFFu
#define TIMER_INT_ENABLE_SHIFT 2u

// 'h6
#define TIMER_INT_CLEAR_REG_OFFSET 12u
#define TIMER_INT_CLEAR_OFFSET TIMER_INT_CLEAR_REG_OFFSET
#define TIMER_INT_CLEAR_MASK 0xFFFFFFFFu
#define TIMER_INT_CLEAR_SHIFT 0u

// 'h7
#define TIMER_RIS_REG_OFFSET 16u
#define TIMER_RIS_OFFSET TIMER_RIS_REG_OFFSET
#define TIMER_RIS_MASK 0xFFFFFFFFu
#define TIMER_RIS_SHIFT 0u

// 'h8
#define TIMER_MIS_REG_OFFSET 20u
#define TIMER_MIS_OFFSET TIMER_MIS_REG_OFFSET
#define TIMER_MIS_MASK 0xFFFFFFFFu
#define TIMER_MIS_SHIFT 0u

// 'h9
#define TIMER_PRESCALE_REG_OFFSET 24u
#define TIMER_PRESCALE_OFFSET TIMER_PRESCALE_REG_OFFSET
#define TIMER_PRESCALE_MASK 0xFFFFFFFFu
#define TIMER_PRESCALE_SHIFT 0u
#endif
