#ifndef TSECORE_REG_H
#define TSECORE_REG_H

//------------------------------------------------------------------------------
// CoreTSE AHB
//------------------------------------------------------------------------------
#define CORETSE_MAC_MACConfiguration1_REG_OFFSET 0x0
#define CORETSE_MAC_MACConfiguration1_OFFSET \
    CORETSE_MAC_MACConfiguration1_REG_OFFSET
#define CORETSE_MAC_MACConfiguration1_MASK 0xFFFFFFFFu
#define CORETSE_MAC_MACConfiguration1_SHIFT 0u

#define CORETSE_MAC_MACConfiguration2_REG_OFFSET 0x004
#define CORETSE_MAC_MACConfiguration2_OFFSET \
    CORETSE_MAC_MACConfiguration2_REG_OFFSET
#define CORETSE_MAC_MACConfiguration2_MASK 0xFFFFFFFFu
#define CORETSE_MAC_MACConfiguration2_SHIFT 0u

#define CORETSE_MAC_A_MCXFIFO_REG_OFFSET 0x48
#define CORETSE_MAC_A_MCXFIFO_OFFSET CORETSE_MAC_A_MCXFIFO_REG_OFFSET
#define CORETSE_MAC_A_MCXFIFO_MASK 0xFFFFFFFFu
#define CORETSE_MAC_A_MCXFIFO_SHIFT 0u

#define CORETSE_MAC_TR64_REG_OFFSET 0x80
#define CORETSE_MAC_TR64_OFFSET CORETSE_MAC_TR64_REG_OFFSET
#define CORETSE_MAC_TR64_MASK 0xFFFFFFFFu
#define CORETSE_MAC_TR64_SHIFT 0u

#define CORETSE_MAC_TR127_REG_OFFSET 0x84
#define CORETSE_MAC_TR127_OFFSET CORETSE_MAC_TR127_REG_OFFSET
#define CORETSE_MAC_TR127_MASK 0xFFFFFFFFu
#define CORETSE_MAC_TR127_SHIFT 0u

#define CORETSE_MAC_TR255_REG_OFFSET 0x88
#define CORETSE_MAC_TR255_OFFSET CORETSE_MAC_TR255_REG_OFFSET
#define CORETSE_MAC_TR255_MASK 0xFFFFFFFFu
#define CORETSE_MAC_TR255_SHIFT 0u


#define CORETSE_MAC_TR511_REG_OFFSET 0x8C
#define CORETSE_MAC_TR511_OFFSET CORETSE_MAC_TR511_REG_OFFSET
#define CORETSE_MAC_TR511_MASK 0xFFFFFFFFu
#define CORETSE_MAC_TR511_SHIFT 0u

#define CORETSE_MAC_TR1K_REG_OFFSET 0x90
#define CORETSE_MAC_TR1K_OFFSET CORETSE_MAC_TR1K_REG_OFFSET
#define CORETSE_MAC_TR1K_MASK 0xFFFFFFFFu
#define CORETSE_MAC_TR1K_SHIFT 0u

#define CORETSE_MAC_TRMAX_REG_OFFSET 0x94
#define CORETSE_MAC_TRMAX_OFFSET CORETSE_MAC_TRMAX_REG_OFFSET
#define CORETSE_MAC_TRMAX_MASK 0xFFFFFFFFu
#define CORETSE_MAC_TRMAX_SHIFT 0u

#endif
