# Generate the vendor IP that simulation compiles, without a synthesis run.
#
#   libero SCRIPT:gen_ip.tcl SCRIPT_ARGS:"<target_board> <scripts_list> <work_dir>"
#
# The design instantiates cores that Libero generates from component
# definitions kept beside the SmartDesigns that use them. Synthesis produces
# them as a side effect, into a timestamped build directory; simulation needs
# the same RTL without a place-and-route and without a synthesis licence.
#
# Which components: `verification/ip.yaml`. `make ip` resolves those names to
# the scripts to source -- the build's own IP scripts that a SmartDesign needs
# first, then each component definition -- and passes them here in order, one
# typed line each (`src` an RTL directory to link, `tcl` a build script, `def`
# a definition), so nothing in this script names a particular core. It generates into a scratch
# project; `verification/record_ip.py --collect` then copies each component's
# sources out and writes the lockfile recording what it was generated from.

set target_board [lindex $argv 0]
set list_file    [lindex $argv 1]
set work_dir     [lindex $argv 2]

if {$target_board eq "" || $list_file eq "" || $work_dir eq ""} {
    puts "usage: SCRIPT_ARGS:\"<target_board> <definitions_list> <work_dir>\""
    exit 1
}

set origin_dir [file normalize "."]
set fh [open $list_file r]
set definitions [split [string trim [read $fh]] "\n"]
close $fh
if {[llength $definitions] == 0 || [lindex $definitions 0] eq ""} {
    puts "ERROR: no component definitions listed in $list_file"
    exit 1
}

# The same device settings the build uses, read from the same files. Restating
# them here would be a second definition of the device, and a core generated
# for a different part is exactly the staleness the lockfiles exist to catch.
source "${origin_dir}/script/common/proj_util.tcl"
source "${origin_dir}/script/${target_board}/proj_config.tcl"

file delete -force $work_dir

new_project                                            \
    -name              "ip_gen"                        \
    -location          "$work_dir"                     \
    -family            "$proj::die_family"             \
    -die               "$proj::die_name"               \
    -package           "$proj::die_package"            \
    -die_voltage       "$proj::die_voltage"            \
    -speed             "$proj::die_speed"              \
    -part_range        "$proj::die_part_range"         \
    -hdl               "$proj::hdl_lang"               \
    -block_mode        "$proj::block_mode"             \
    -adv_options       "$proj::restrict_probe_pins"    \
    -adv_options       "$proj::restrict_spi_pins"      \
    -adv_options       "$proj::sys_ctrl_suspend"       \
    -adv_options       "$proj::reserve_migration_pins" \
    -adv_options       "$proj::io_default_std"         \
    -adv_options       "$proj::temp_range"             \
    -adv_options       "$proj::vcci_1p2_volt_range"    \
    -adv_options       "$proj::vcci_1p5_volt_range"    \
    -adv_options       "$proj::vcci_1p8_volt_range"    \
    -adv_options       "$proj::vcci_2p5_volt_range"    \
    -adv_options       "$proj::vcci_3p3_volt_range"    \
    -adv_options       "$proj::volt_range"

# create_and_configure_core generates the RTL as it runs, so there is no
# separate generate step. Definitions are sourced rather than copied: a copy
# is a second definition, and the two diverge the first time one is edited.
# The cores come from the vault `make ip` names, by default this checkout's own,
# which it fills from the build's script/common/download.tcl. A core missing
# from the vault fails here with Libero's message naming it.
foreach line $definitions {
    set kind [lindex $line 0]
    set path [lindex $line 1]
    if {$kind eq "src"} {
        # The build's own proc, as synth.tcl calls it for every IP block.
        puts "Linking [file tail [file dirname $path]]/[file tail $path]"
        proj::set_src_files -folder_path $path
    } elseif {$kind eq "def" &&
              [file exists "${work_dir}/component/work/[file rootname [file tail $path]]"]} {
        # A build script sourced this same definition already (a DMA's IP
        # script creates the COREFIFO it instantiates); Libero refuses to
        # create a component twice.
        puts "Already generated by a build script: [file tail $path]"
    } else {
        puts "Sourcing [file tail $path]"
        source $path
    }
}

# The scratch project is not deleted here: Libero writes the project file out
# again after the script returns. `make ip` collects from it and removes it
# once Libero has exited.
puts "Generated [llength $definitions] component(s) under ${work_dir}/component"
