"""Clock and reset helpers shared by the housekeeper testbenches.

The clock itself is generated by the simulation wrapper, not here: driving it
from Python costs a callback per edge, and the housekeeper spends fifty
million edges waiting for `HK-SEQ-01`'s one-second hold-off.

`advance` exists for the same reason. `ClockCycles(clk, 50_000_000)` wakes
cocotb on every one of those edges; a single timed wait wakes it once, and the
difference on this design is 145,854 cycles/s against 239,202.
"""

from __future__ import annotations

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import ClockCycles, RisingEdge, Timer

#: The housekeeper runs from a 50 MHz oscillator (see uart_ctrl.sv SECOND).
CLK_PERIOD_NS = 20
CLK_FREQ_HZ = 50_000_000


def start_clock(clk, period_ns: int = CLK_PERIOD_NS):
    """Start a free-running clock on ``clk`` and return the driver task."""
    return cocotb.start_soon(Clock(clk, period_ns, unit="ns").start())


async def advance(clk, seconds: float = 0.0, cycles: int = 0) -> None:
    """Let the device run, without waking cocotb on every clock edge.

    Realigns to a rising edge before returning, so a caller that samples
    immediately afterwards sees a settled value rather than one mid-flight.
    """
    total_ns = seconds * 1e9 + cycles * CLK_PERIOD_NS
    if total_ns > 0:
        await Timer(round(total_ns), unit="ns")
    await RisingEdge(clk)


async def reset(clk, rstn, cycles: int = 10, active_low: bool = True) -> None:
    """Assert then deassert a reset, leaving the DUT ready on the next edge."""
    rstn.value = 0 if active_low else 1
    await ClockCycles(clk, cycles)
    rstn.value = 1 if active_low else 0
    await ClockCycles(clk, cycles)


async def until(clk, predicate, *, timeout_s: float, poll_ms: float = 1.0,
                describe=None):
    """Run until `predicate()` holds, returning how long that took.

    A fixed wait long enough for the slowest case is a fixed wait that hides
    when something gets slower, and one tuned to the fastest is a test that
    fails on a machine under load. Polling reports the time, so a test can
    both proceed as soon as the device is ready and say how long it waited.

    `poll_ms` is a compromise, not a resolution: waking cocotb on every edge
    is what made these runs sixteen minutes. At the default the device is
    sampled every fifty thousand clocks, which is finer than any board delay
    here and coarse enough to cost nothing.
    """
    waited = 0.0
    while True:
        await advance(clk, seconds=poll_ms / 1000.0)
        waited += poll_ms / 1000.0
        if predicate():
            return waited
        if waited >= timeout_s:
            # What is still outstanding, not merely that something is. A
            # timeout saying only that it timed out sends the reader back to
            # the waveform for something the test already knew.
            detail = ": %s" % describe() if describe else ""
            raise TimeoutError(
                "still not true after %g s of simulated time%s"
                % (waited, detail))


async def elapse(seconds: float = 0.0, cycles: int = 0) -> None:
    """Let time pass without waiting for a clock edge.

    `advance` realigns to a rising edge before returning, which is what a test
    wants almost always -- and is a hang when the clock has been stopped.
    `HK-OFFNOM-04` is precisely about a stopped clock, so it needs a wait that
    does not assume one is running.
    """
    total_ns = seconds * 1e9 + cycles * CLK_PERIOD_NS
    if total_ns > 0:
        await Timer(round(total_ns), unit="ns")
