# Exporting core axi_read_mux to TCL
# Exporting Create HDL core command for module axi_read_mux
create_hdl_core -file "[file normalize [file join [file dirname [info script]] ./../src/axi_read_mux.sv]]" -module {axi_read_mux} -library {work} -package {}
# Exporting BIF information of  HDL core command for module axi_read_mux
hdl_core_add_bif -hdl_core_name {axi_read_mux} -bif_definition {AXI4:AMBA:AMBA4:slave} -bif_name {AXI4_S0} -signal_map {\
"AWID:s0_awid" \
"AWADDR:s0_awaddr" \
"AWLEN:s0_awlen" \
"AWSIZE:s0_awsize" \
"AWBURST:s0_awburst" \
"AWVALID:s0_awvalid" \
"AWREADY:s0_awready" \
"WDATA:s0_wdata" \
"WSTRB:s0_wstrb" \
"WLAST:s0_wlast" \
"WVALID:s0_wvalid" \
"WREADY:s0_wready" \
"BID:s0_bid" \
"BRESP:s0_bresp" \
"BVALID:s0_bvalid" \
"BREADY:s0_bready" \
"ARID:s0_arid" \
"ARADDR:s0_araddr" \
"ARLEN:s0_arlen" \
"ARSIZE:s0_arsize" \
"ARBURST:s0_arburst" \
"ARVALID:s0_arvalid" \
"ARREADY:s0_arready" \
"RID:s0_rid" \
"RDATA:s0_rdata" \
"RRESP:s0_rresp" \
"RLAST:s0_rlast" \
"RVALID:s0_rvalid" \
"RREADY:s0_rready" }
hdl_core_add_bif -hdl_core_name {axi_read_mux} -bif_definition {AXI4:AMBA:AMBA4:slave} -bif_name {AXI4_S1} -signal_map {\
"AWID:s1_awid" \
"AWADDR:s1_awaddr" \
"AWLEN:s1_awlen" \
"AWSIZE:s1_awsize" \
"AWBURST:s1_awburst" \
"AWVALID:s1_awvalid" \
"AWREADY:s1_awready" \
"WDATA:s1_wdata" \
"WSTRB:s1_wstrb" \
"WLAST:s1_wlast" \
"WVALID:s1_wvalid" \
"WREADY:s1_wready" \
"BID:s1_bid" \
"BRESP:s1_bresp" \
"BVALID:s1_bvalid" \
"BREADY:s1_bready" \
"ARID:s1_arid" \
"ARADDR:s1_araddr" \
"ARLEN:s1_arlen" \
"ARSIZE:s1_arsize" \
"ARBURST:s1_arburst" \
"ARVALID:s1_arvalid" \
"ARREADY:s1_arready" \
"RID:s1_rid" \
"RDATA:s1_rdata" \
"RRESP:s1_rresp" \
"RLAST:s1_rlast" \
"RVALID:s1_rvalid" \
"RREADY:s1_rready" }
hdl_core_add_bif -hdl_core_name {axi_read_mux} -bif_definition {AXI4:AMBA:AMBA4:mirroredSlave} -bif_name {AXI4_M} -signal_map {\
"AWID:m_awid" \
"AWADDR:m_awaddr" \
"AWLEN:m_awlen" \
"AWSIZE:m_awsize" \
"AWBURST:m_awburst" \
"AWVALID:m_awvalid" \
"AWREADY:m_awready" \
"WDATA:m_wdata" \
"WSTRB:m_wstrb" \
"WLAST:m_wlast" \
"WVALID:m_wvalid" \
"WREADY:m_wready" \
"BID:m_bid" \
"BRESP:m_bresp" \
"BVALID:m_bvalid" \
"BREADY:m_bready" \
"ARID:m_arid" \
"ARADDR:m_araddr" \
"ARLEN:m_arlen" \
"ARSIZE:m_arsize" \
"ARBURST:m_arburst" \
"ARVALID:m_arvalid" \
"ARREADY:m_arready" \
"RID:m_rid" \
"RDATA:m_rdata" \
"RRESP:m_rresp" \
"RLAST:m_rlast" \
"RVALID:m_rvalid" \
"RREADY:m_rready" }
