# Exporting core axi_read_demux to TCL
# Exporting Create HDL core command for module axi_read_demux
create_hdl_core -file "[file normalize [file join [file dirname [info script]] ./../src/axi_read_demux.sv]]" -module {axi_read_demux} -library {work} -package {}
# Exporting BIF information of  HDL core command for module axi_read_demux
hdl_core_add_bif -hdl_core_name {axi_read_demux} -bif_definition {AXI4:AMBA:AMBA4:master} -bif_name {AXI4_M0} -signal_map {\
"AWID:m0_awid" \
"AWADDR:m0_awaddr" \
"AWLEN:m0_awlen" \
"AWSIZE:m0_awsize" \
"AWBURST:m0_awburst" \
"AWVALID:m0_awvalid" \
"AWREADY:m0_awready" \
"WDATA:m0_wdata" \
"WSTRB:m0_wstrb" \
"WLAST:m0_wlast" \
"WVALID:m0_wvalid" \
"WREADY:m0_wready" \
"BID:m0_bid" \
"BRESP:m0_bresp" \
"BVALID:m0_bvalid" \
"BREADY:m0_bready" \
"ARID:m0_arid" \
"ARADDR:m0_araddr" \
"ARLEN:m0_arlen" \
"ARSIZE:m0_arsize" \
"ARBURST:m0_arburst" \
"ARVALID:m0_arvalid" \
"ARREADY:m0_arready" \
"RID:m0_rid" \
"RDATA:m0_rdata" \
"RRESP:m0_rresp" \
"RLAST:m0_rlast" \
"RVALID:m0_rvalid" \
"RREADY:m0_rready" }
hdl_core_add_bif -hdl_core_name {axi_read_demux} -bif_definition {AXI4:AMBA:AMBA4:master} -bif_name {AXI4_M1} -signal_map {\
"AWID:m1_awid" \
"AWADDR:m1_awaddr" \
"AWLEN:m1_awlen" \
"AWSIZE:m1_awsize" \
"AWBURST:m1_awburst" \
"AWVALID:m1_awvalid" \
"AWREADY:m1_awready" \
"WDATA:m1_wdata" \
"WSTRB:m1_wstrb" \
"WLAST:m1_wlast" \
"WVALID:m1_wvalid" \
"WREADY:m1_wready" \
"BID:m1_bid" \
"BRESP:m1_bresp" \
"BVALID:m1_bvalid" \
"BREADY:m1_bready" \
"ARID:m1_arid" \
"ARADDR:m1_araddr" \
"ARLEN:m1_arlen" \
"ARSIZE:m1_arsize" \
"ARBURST:m1_arburst" \
"ARVALID:m1_arvalid" \
"ARREADY:m1_arready" \
"RID:m1_rid" \
"RDATA:m1_rdata" \
"RRESP:m1_rresp" \
"RLAST:m1_rlast" \
"RVALID:m1_rvalid" \
"RREADY:m1_rready" }
hdl_core_add_bif -hdl_core_name {axi_read_demux} -bif_definition {AXI4:AMBA:AMBA4:slave} -bif_name {AXI4_S} -signal_map {\
"AWID:s_awid" \
"AWADDR:s_awaddr" \
"AWLEN:s_awlen" \
"AWSIZE:s_awsize" \
"AWBURST:s_awburst" \
"AWVALID:s_awvalid" \
"AWREADY:s_awready" \
"WDATA:s_wdata" \
"WSTRB:s_wstrb" \
"WLAST:s_wlast" \
"WVALID:s_wvalid" \
"WREADY:s_wready" \
"BID:s_bid" \
"BRESP:s_bresp" \
"BVALID:s_bvalid" \
"BREADY:s_bready" \
"ARID:s_arid" \
"ARADDR:s_araddr" \
"ARLEN:s_arlen" \
"ARSIZE:s_arsize" \
"ARBURST:s_arburst" \
"ARVALID:s_arvalid" \
"ARREADY:s_arready" \
"RID:s_rid" \
"RDATA:s_rdata" \
"RRESP:s_rresp" \
"RLAST:s_rlast" \
"RVALID:s_rvalid" \
"RREADY:s_rready" }
